-- MySQL Script generated by MySQL Workbench
-- Fri Apr  4 14:47:06 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lufthansa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lufthansa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lufthansa` DEFAULT CHARACTER SET utf8 ;
USE `lufthansa` ;

-- -----------------------------------------------------
-- Table `lufthansa`.`Aircrafts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lufthansa`.`Aircrafts` ;

CREATE TABLE IF NOT EXISTS `lufthansa`.`Aircrafts` (
  `Aircraft_code` VARCHAR(3) NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`Aircraft_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lufthansa`.`Airlines`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lufthansa`.`Airlines` ;

CREATE TABLE IF NOT EXISTS `lufthansa`.`Airlines` (
  `Airline_code` VARCHAR(3) NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`Airline_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lufthansa`.`Status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lufthansa`.`Status` ;

CREATE TABLE IF NOT EXISTS `lufthansa`.`Status` (
  `Status_code` VARCHAR(3) NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`Status_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lufthansa`.`Cities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lufthansa`.`Cities` ;

CREATE TABLE IF NOT EXISTS `lufthansa`.`Cities` (
  `City_id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`City_id`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lufthansa`.`Countries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lufthansa`.`Countries` ;

CREATE TABLE IF NOT EXISTS `lufthansa`.`Countries` (
  `Country_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`Country_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lufthansa`.`Airports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lufthansa`.`Airports` ;

CREATE TABLE IF NOT EXISTS `lufthansa`.`Airports` (
  `Airport_code` VARCHAR(45) NOT NULL,
  `Airport_name` VARCHAR(45) NULL,
  `City_id` INT NULL,
  `Country_id` INT NULL,
  `latitude` FLOAT NULL,
  `longitude` FLOAT NULL,
  INDEX `city_id_fk_idx` (`City_id` ASC) VISIBLE,
  INDEX `coountry_id_fk_idx` (`Country_id` ASC) VISIBLE,
  PRIMARY KEY (`Airport_code`),
  CONSTRAINT `city_id_fk`
    FOREIGN KEY (`City_id`)
    REFERENCES `lufthansa`.`Cities` (`City_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `coountry_id_fk`
    FOREIGN KEY (`Country_id`)
    REFERENCES `lufthansa`.`Countries` (`Country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lufthansa`.`Flights`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lufthansa`.`Flights` ;

CREATE TABLE IF NOT EXISTS `lufthansa`.`Flights` (
  `Flight_id` INT NOT NULL AUTO_INCREMENT,
  `Airport_departure_id` VARCHAR(3) NULL,
  `Airport_arrival_id` VARCHAR(3) NULL,
  `Scheduled_departure_time` TIMESTAMP NULL,
  `Actual_departure_time` TIMESTAMP NULL,
  `Scheduled_arrival_time` TIMESTAMP NULL,
  `Actual_arrival_time` TIMESTAMP NULL,
  `Departure_time_status_code` VARCHAR(5) NULL,
  `Terminal` VARCHAR(45) NULL,
  `Gate` VARCHAR(4) NULL,
  `Flight_completion` VARCHAR(45) NULL,
  `Current_position_latitude` FLOAT NULL,
  `Current_position_longitude` FLOAT NULL,
  `Airline_code` VARCHAR(3) NULL,
  `Aircraft_code` VARCHAR(3) NULL,
  `Service_type` ENUM('Passenger', 'Cargo') NULL,
  `Arrival_time_status_code` VARCHAR(5) NULL,
  `Flight_status_code` VARCHAR(45) NULL,
  `Flight_number` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Flight_id`),
  INDEX `aircraft_id_fk_idx` (`Aircraft_code` ASC) VISIBLE,
  INDEX `airline_id_fk_idx` (`Airline_code` ASC) VISIBLE,
  INDEX `status_code_fk_idx` (`Departure_time_status_code` ASC) VISIBLE,
  INDEX `airport_arr_id_fk_idx` (`Airport_arrival_id` ASC) VISIBLE,
  INDEX `airport_dep_id_fk_idx` (`Airport_departure_id` ASC) VISIBLE,
  INDEX `status_time_arr_fk_idx` (`Arrival_time_status_code` ASC) VISIBLE,
  INDEX `flight_status_fk_idx` (`Flight_status_code` ASC) VISIBLE,
  INDEX `flight_number_uq` (`Flight_number` ASC, `Airline_code` ASC) VISIBLE,
  CONSTRAINT `aircraft_id_fk`
    FOREIGN KEY (`Aircraft_code`)
    REFERENCES `lufthansa`.`Aircrafts` (`Aircraft_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `airline_id_fk`
    FOREIGN KEY (`Airline_code`)
    REFERENCES `lufthansa`.`Airlines` (`Airline_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `status_time_dep_fk`
    FOREIGN KEY (`Departure_time_status_code`)
    REFERENCES `lufthansa`.`Status` (`Status_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `airport_arr_id_fk`
    FOREIGN KEY (`Airport_arrival_id`)
    REFERENCES `lufthansa`.`Airports` (`Airport_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `airport_dep_id_fk`
    FOREIGN KEY (`Airport_departure_id`)
    REFERENCES `lufthansa`.`Airports` (`Airport_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `status_time_arr_fk`
    FOREIGN KEY (`Arrival_time_status_code`)
    REFERENCES `lufthansa`.`Status` (`Status_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `flight_status_fk`
    FOREIGN KEY (`Flight_status_code`)
    REFERENCES `lufthansa`.`Status` (`Status_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
